export const inimigos = [
  {
    x: 900,
    y: 470 - 45,
    width: 40,
    height: 80,
    color: "red",
    speed: 0.7,
    isAlive: true,
    isFlashing: false,
    attackCooldown: false,
  },
  {
    x: 1600,
    y: 470 - 45,
    width: 40,
    height: 80,
    color: "red",
    speed: 0.7,
    isAlive: true,
    isFlashing: false,
    attackCooldown: false,
  },
  {
    x: 2300,
    y: 470 - 45,
    width: 40,
    height: 80,
    color: "red",
    speed: 0.7,
    isAlive: true,
    isFlashing: false,
    attackCooldown: false,
  },
];